---
abstract: 'Plugins LeonT uses for pure perl modules'
author:
  - 'Leon Timmermans <leont@cpan.org>'
build_requires:
  File::Find: 0
  File::Temp: 0
  Test::More: 0
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300000, CPAN::Meta::Converter version 2.110440'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-PluginBundle-LEONT-PP
requires:
  Dist::Zilla: 0
  Dist::Zilla::PluginBundle::Basic: 0
  Dist::Zilla::PluginBundle::LEONT::Base: 0.004
  Dist::Zilla::Role::PluginBundle::Easy: 0
  Moose: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-PluginBundle-LEONT-PP
  repository: git://github.com/Leont/dist-zilla-pluginbundle-LEONT-PP.git
version: 0.002
